# Generated by Django 4.0.4 on 2022-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=200)),
                ('job_descr', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_descr', models.CharField(max_length=200)),
                ('amount_due', models.IntegerField(default='$200')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
