# Generated by Django 4.0.4 on 2022-06-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_add_company_individual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_company',
        ),
    ]
