# Generated by Django 4.0.4 on 2022-06-02 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_delete_add_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
